{
 "title": "Kafka Demo Dashboard",
 "tags": [
  "kafka",
  "demo",
  "nestjs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_version_info" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  { "title": "Kafka Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(kafka_messages_produced_total[1m])",
     "legendFormat": "Produced {{topic}}"
    },
    {
     "expr": "rate(kafka_messages_consumed_total[1m])",
     "legendFormat": "Consumed {{topic}}"
    }
   ]
  },
  {
   "title": "Avg Message Processing Time(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(kafka_message_processing_duration_seconds_sum[1m]) / rate(kafka_message_processing_duration_seconds_count[1m])",
     "legendFormat": "Avg processing time {{consumer_group}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active WebSocket Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "websocket_active_connections", "legendFormat": "Active Sockets" }
   ]
  }
 ]
}